name: Website

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - run: sbt docs/mdoc
