name: Website

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - uses: actions/setup-node@v3
      - run: ls
      - run: sbt docs/mdoc
